### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by 07JP27** [jt-t/s4#2]
【必須-Required】
- [ ] Swagger or API BlueprintでAPIドキュメントページを自動作成する
- [ ] 認証(アクセストークンとリフレッシュトークン)の実装
- [ ] 認証をかけるAPIとかけないAPIを簡単に切り替えられるか？(アトリビュートつければOKみたいな)
- [ ] EntityFramework的なクエリ文でDB操作ができるか(SQL文を直接発行はSQLインジェクション発生の可能性があるためNG)
- [ ] ログはどんな感じで記録できるか
- [ ] WPのDBに接続して情報を吸い取れるか

【任意-Optional】
- [ ] 将来的にAPIを外部開発者に提供するときの認証と制限(1分に１回しか呼べないとか)
